name: test

on:
  push:
  pull_request:

permissions:
  contents: read

jobs:
  shell-tests:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run tests
        run: ./tests/test.sh
